# Generated by Django 3.2.9 on 2021-11-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('imagem', models.ImageField(upload_to='')),
                ('saldo', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('setor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.FloatField()),
                ('quantidade', models.BigIntegerField()),
                ('codigo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scme.produto')),
                ('codigo_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scme.vendedor')),
            ],
        ),
    ]
