# Generated by Django 3.2.9 on 2021-11-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scme', '0002_auto_20211124_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='valor_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
